name: Despliegue Automático a Hospedando

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🚀 Subir cambios a cPanel (public_html)
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
    steps:
      - name: 🚚 Obtener código fuente
        uses: actions/checkout@v4

      - name: 📂 Sincronizar archivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
